# Generated by Django 3.1.1 on 2020-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app_m', '0009_auto_20200930_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(verbose_name='comment text'),
        ),
    ]
